language: python
python:
  - "2.6"
  - "2.7"

# command to install dependencies
install: 
  - "pip install https://github.com/aobo711/bootstrap-django-admin/zipball/master"
  - "pip install -r requirements.txt --use-mirrors"

# command to run tests
script: python manage.py test library_collection
