version: 0.2

phases:
  build:
    commands:
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.us-west-2.amazonaws.com
      - docker build -t registry .
      - docker tag registry:latest $AWS_ACCOUNT_ID.dkr.ecr.us-west-2.amazonaws.com/registry:latest
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.us-west-2.amazonaws.com/registry:latest
  # post_build:
  #   commands:
  #     - aws ecs update-service --cluster calisphere-stage --service registry-stage-service --force-new-deployment