services:

  registry-app:
    build: 
      context: .
    container_name: registry
    ports:
      - 8000:8000
    environment:
      DJANGO_SETTINGS_MODULE: collection_registry.test_settings
    env_file:
      - docker.env