# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-08 23:20
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('library_collection', '0011_auto_20181015_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='google_analytics_tracking_code',
            field=models.CharField(blank=True, help_text='Enable tracking of your digital assets hosted in the UCLDC by entering your Google Analytics tracking code.', max_length=64),
        ),
        migrations.AlterField(
            model_name='collection',
            name='dcmi_type',
            field=models.CharField(choices=[('C', 'Collection'), ('D', 'Dataset'), ('E', 'Event'), ('I', 'Image'), ('R', 'Interactive Resource'), ('F', 'Moving Image'), ('V', 'Service'), ('S', 'Software'), ('A', 'Sound'), ('T', 'Text'), ('P', 'Physical Object'), ('X', '-----')], default='X', help_text='DCMI Type for objects in this collection', max_length=1),
        ),
        migrations.AlterField(
            model_name='collection',
            name='disqus_shortname_prod',
            field=models.CharField(blank=True, help_text='put disqus on production with this shortcode (from disqus admin)', max_length=64),
        ),
        migrations.AlterField(
            model_name='collection',
            name='disqus_shortname_test',
            field=models.CharField(blank=True, help_text='put disqus on test with this shortcode', max_length=64),
        ),
        migrations.AlterField(
            model_name='collection',
            name='enrichments_item',
            field=models.TextField(blank=True, help_text='Enhancement chain to run on individual harvested items.'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='extent',
            field=models.BigIntegerField(blank=True, help_text='must be entered in bytes, will take abbreviations later', null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='featured',
            field=models.BooleanField(default=False, help_text='Collection featured on repository home page'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='formats',
            field=models.ManyToManyField(blank=True, help_text='File formats for DAMS ingest', to='library_collection.Format'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='harvest_exception_notes',
            field=models.TextField(blank=True, help_text='Notes on processing quirks'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='harvest_extra_data',
            field=models.CharField(blank=True, help_text='extra text data needed for the particular type of harvest.', max_length=511),
        ),
        migrations.AlterField(
            model_name='collection',
            name='harvest_type',
            field=models.CharField(choices=[('X', 'None'), ('OAC', 'Legacy OAC'), ('OAI', 'OAI-PMH'), ('SLR', 'Solr Index'), ('MRC', 'MARC21'), ('NUX', 'Shared DAMS'), ('ALX', 'Aleph MARC XML'), ('SFX', 'UCSF XML Search Results (tobacco)'), ('UCB', 'Solr Generic - cursorMark'), ('PRE', 'Preservica CMIS Atom Feed'), ('FLK', 'Flickr Api All Public Photos'), ('YTB', 'YouTube Api - Playlist Videos'), ('XML', 'XML File'), ('EMS', 'eMuseum API'), ('UCD', 'UC Davis JSON')], default='X', max_length=3),
        ),
        migrations.AlterField(
            model_name='collection',
            name='hosted',
            field=models.CharField(blank=True, help_text='Indicate format and output', max_length=255, verbose_name='Existing metadata (Format/Output)'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='local_id',
            field=models.CharField(blank=True, help_text='used for google analytics subsetting', max_length=1028),
        ),
        migrations.AlterField(
            model_name='collection',
            name='merritt_extra_data',
            field=models.CharField(blank=True, help_text='nuxeo path for Merritt harvest (usually the same as Harvest extra data)', max_length=511),
        ),
        migrations.AlterField(
            model_name='collection',
            name='merritt_id',
            field=models.CharField(blank=True, help_text='Merritt Id (ARK)', max_length=100),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Collection Title'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='repository',
            field=models.ManyToManyField(blank=True, to='library_collection.Repository', verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='rights_status',
            field=models.CharField(choices=[('CR', 'copyrighted'), ('PD', 'public domain'), ('UN', 'copyright unknown'), ('X', '-----')], default='X', max_length=3),
        ),
        migrations.AlterField(
            model_name='collection',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=('name', 'description')),
        ),
        migrations.AlterField(
            model_name='collection',
            name='staging_notes',
            field=models.TextField(blank=True, default='', help_text='Possible support needed by contributor'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='url_harvest',
            field=models.URLField(blank=True, max_length=255, verbose_name='Harvest Endpoint'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='url_local',
            field=models.URLField(blank=True, help_text='Collection homepage URL', max_length=255),
        ),
        migrations.AlterField(
            model_name='collection',
            name='url_oac',
            field=models.URLField(blank=True, help_text='OAC finding aid URL', max_length=255),
        ),
        migrations.AlterField(
            model_name='collectioncustomfacet',
            name='facet_field',
            field=models.CharField(choices=[('contributor_ss', 'contributor'), ('coverage_ss', 'coverage'), ('creator_ss', 'creator'), ('date_ss', 'date'), ('extent_ss', 'extent'), ('format_ss', 'format'), ('genre_ss', 'genre'), ('language_ss', 'language'), ('location_ss', 'location'), ('publisher_ss', 'publisher'), ('relation_ss', 'relation'), ('rights_ss', 'rights'), ('rights_holder_ss', 'rights_holder'), ('rights_note_ss', 'rights_note'), ('rights_date_ss', 'rights_date'), ('source_ss', 'source'), ('subject_ss', 'subject'), ('temporal_ss', 'temporal')], max_length=20),
        ),
        migrations.AlterField(
            model_name='repository',
            name='google_analytics_tracking_code',
            field=models.CharField(blank=True, help_text='Enable tracking of your digital assets hosted in the UCLDC by entering your Google Analytics tracking code.', max_length=64),
        ),
        migrations.AlterField(
            model_name='repository',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name'),
        ),
    ]
