# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-10-13 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_collection', '0014_auto_20190729_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='repository',
            field=models.ManyToManyField(to='library_collection.Repository', verbose_name='Unit'),
        ),
    ]
