# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-12-01 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_collection', '0018_collection_mapper_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='metadata_density_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='metadata_density_score_last_updated',
            field=models.DateTimeField(blank=True, help_text='Last time metadata density score was updated', null=True),
        ),
    ]
