# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-02-18 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_collection', '0019_auto_20221130_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='rikolti_mapper_type',
            field=models.CharField(blank=True, help_text='Matches module name in Rikolti', max_length=511, null=True),
        ),
    ]
