# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-11-02 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_collection', '0021_auto_20230414_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='harvest_exception_notes',
            field=models.TextField(blank=True, help_text='Notes on processing quirks', null=True),
        ),
    ]
