# Generated by Django 3.2.23 on 2024-03-06 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_collection', '0025_library_collection_harvestrun_harvesttrigger'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HarvestRun',
        ),
    ]
