# Generated by Django 3.2.23 on 2024-02-06 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_collection', '0025_library_collection_harvestrun'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='harvestrun',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='harvestrun',
            name='dag_id',
        ),
        migrations.RemoveField(
            model_name='harvestrun',
            name='dag_run_id',
        ),
        migrations.CreateModel(
            name='HarvestTrigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dag_id', models.CharField(max_length=255)),
                ('hostname', models.CharField(max_length=255)),
                ('stdout', models.TextField(blank=True)),
                ('stderr', models.TextField(blank=True)),
                ('dag_run_id', models.CharField(blank=True, max_length=255, null=True)),
                ('airflow_execution_time', models.DateTimeField(blank=True, null=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_collection.collection')),
            ],
        ),
        migrations.AddField(
            model_name='harvestrun',
            name='harvest_trigger',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='library_collection.harvesttrigger'),
            preserve_default=False,
        ),
    ]
