# Generated by Django 3.2.23 on 2024-03-07 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_collection', '0026_delete_harvestrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='HarvestRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dag_id', models.CharField(max_length=255)),
                ('dag_run_id', models.CharField(max_length=255)),
                ('logical_date', models.DateTimeField()),
                ('dag_run_conf', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'running'), ('succeeded', 'succeeded'), ('failed', 'failed')], default='running', max_length=255, verbose_name='Manually update status')),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='library_collection.collection')),
                ('harvest_trigger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='library_collection.harvesttrigger')),
            ],
        ),
        migrations.CreateModel(
            name='HarvestEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('try_number', models.IntegerField(blank=True, null=True)),
                ('map_index', models.IntegerField(blank=True, null=True)),
                ('rikolti_message', models.TextField()),
                ('error', models.BooleanField(default=False)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='library_collection.collection')),
                ('harvest_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='library_collection.harvestrun')),
            ],
        ),
    ]
