# Generated by Django 3.2.23 on 2024-03-07 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_collection', '0027_harvestevent_harvestrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvestevent',
            name='sns_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='harvestevent',
            name='sns_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='harvestevent',
            name='sqs_message',
            field=models.TextField(blank=True),
        ),
    ]
