# Generated by Django 3.2.23 on 2024-03-07 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_collection', '0028_auto_20240306_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvestrun',
            name='host',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
