# Generated by Django 3.2.25 on 2024-06-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_collection', '0029_harvestrun_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='production_target_version',
            field=models.CharField(blank=True, help_text='s3 path to metadata version to target for production. Updating this field will trigger the Publish Collection task.', max_length=255),
        ),
        migrations.AlterField(
            model_name='collection',
            name='ready_for_publication',
            field=models.BooleanField(default=False, help_text='Deprecated'),
        ),
    ]
