# Generated by Django 3.2.25 on 2024-07-11 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_collection', '0030_auto_20240628_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='production_target_version',
            field=models.CharField(blank=True, help_text='s3 path to metadata version to target for production. Updating this field will trigger the Publish Collection task.', max_length=512),
        ),
    ]
