# Generated by Django 3.2.25 on 2025-05-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_collection', '0031_alter_collection_production_target_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='campus',
            name='address1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='campus',
            name='address2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='campus',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='campus',
            name='county',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='campus',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='campus',
            name='email',
            field=models.CharField(blank=True, max_length=63),
        ),
        migrations.AddField(
            model_name='campus',
            name='fax',
            field=models.CharField(blank=True, max_length=63),
        ),
        migrations.AddField(
            model_name='campus',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campus',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campus',
            name='phone',
            field=models.CharField(blank=True, max_length=63),
        ),
        migrations.AddField(
            model_name='campus',
            name='url',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='campus',
            name='zip4',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='repository',
            name='address1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='repository',
            name='address2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='repository',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='repository',
            name='county',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='repository',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='email',
            field=models.CharField(blank=True, max_length=63),
        ),
        migrations.AddField(
            model_name='repository',
            name='fax',
            field=models.CharField(blank=True, max_length=63),
        ),
        migrations.AddField(
            model_name='repository',
            name='ga',
            field=models.CharField(blank=True, help_text='Tracking via Google Analytics has been disabled as of 2023; code displayed for historical reference purposes only.', max_length=64),
        ),
        migrations.AddField(
            model_name='repository',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='phone',
            field=models.CharField(blank=True, max_length=63),
        ),
        migrations.AddField(
            model_name='repository',
            name='url',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='repository',
            name='zip4',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='campus',
            name='google_analytics_tracking_code',
            field=models.CharField(blank=True, help_text='Tracking via Google Analytics has been disabled as of 2023; code displayed for historical reference purposes only.', max_length=64),
        ),
        migrations.AlterField(
            model_name='collection',
            name='production_target_version',
            field=models.CharField(blank=True, help_text='s3 path to metadata version to target for production.', max_length=512),
        ),
    ]
