# Generated by Django 3.2.25 on 2025-05-09 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_collection', '0032_auto_20250507_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='ga',
        ),
    ]
