# Generated by Django 3.2.25 on 2026-07-08 17:46

from django.db import migrations, models
from django.db.models import F, Value
from django.db.models.functions import Coalesce, Concat

def copy_field_data(apps, _schema_editor):
    CollectionModel = apps.get_model('library_collection', 'Collection')
    CollectionModel.objects.all().update(
        legacy_harvest_notes=Concat(
            Value('***enrichments_item***\n'),
            Coalesce(F('enrichments_item'), Value('')),
        )
    )


class Migration(migrations.Migration):

    dependencies = [
        ('library_collection', '0033_remove_repository_ga'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='legacy_harvest_notes',
            field=models.TextField(blank=True, help_text='Notes on legacy harvests, for historical reference'),
        ),
        migrations.RunPython(copy_field_data),
    ]
