# Generated by Django 3.2.25 on 2026-07-08 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_collection', '0034_collection_legacy_harvest_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='mapper_type',
            new_name='legacy_mapper_type',
        ),
    ]
