# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-01 18:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exhibits', '0001_squashed_0007_auto_20180731_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='browseterm',
            name='browse_term_group',
        ),
        migrations.RemoveField(
            model_name='browsetermgroup',
            name='exhibit',
        ),
        migrations.RemoveField(
            model_name='browsetermgroup',
            name='theme',
        ),
        migrations.DeleteModel(
            name='BrowseTerm',
        ),
        migrations.DeleteModel(
            name='BrowseTermGroup',
        ),
    ]
