# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-27 17:44


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibits', '0004_auto_20170619_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibititem',
            name='publish',
            field=models.BooleanField(default=True, verbose_name='Ready for publication?'),
        ),
    ]
