#!/usr/bin/env bash

if [[ -n "$DEBUG" ]]; then 
  set -x
fi

set -o pipefail  # trace ERR through pipes
set -o errtrace  # trace ERR through 'time command' and other functions
set -o nounset   ## set -u : exit the script if you try to use an uninitialised variable
set -o errexit   ## set -e : exit the script if any statement returns a non-true return value

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" # http://stackoverflow.com/questions/59895
cd "$DIR"

# there is no $HOME in monit...
export USER=$(/usr/bin/whoami) # http://codeblog.vurdalakov.net/2010/12/how-to-get-current-user-name-in-bash.html
export HOME=$(getent passwd $USER | cut -d: -f6) # http://stackoverflow.com/a/7359006/1763984

export SHIBSP_LOGGING="$HOME/servers/shibboleth/etc/native.logger"

"$HOME/servers/mod_wsgi-express/apachectl" start